import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Providers } from "../../redux/provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          rel="icon"
          type="image/x-icon"
          href="/assets/images/favicon.png"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/assets/scss/style.css"
          
        />
         <link
          rel="stylesheet"
          type="text/css"
          href="/assets/scss/onboarding.css"
        />
         <link
          rel="stylesheet"
          type="text/css"
          href="/assets/scss/main.css"
        />
          <link
          rel="stylesheet"
          type="text/css"
          href="/assets/scss/sidemenu.css"
        />
      </head>
      <body className={inter.className}>
        <Suspense>
          <Providers>
        {children}
        <Toaster
              position="bottom-center"
              reverseOrder={false}
              gutter={8}
              containerClassName=""
              containerStyle={{}}
              toastOptions={{
                className: "toastr-msg",
                duration: 3000,
                style: { background: "#fff", color: "#363636" },
              }}
            />
        </Providers>
        </Suspense></body>
    </html>
  );
}
