import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import { HeaderRight } from "./_components/HeaderRight";
import LeftbarMenu from "../(components)/LeftbarMenu";
import { Sidebar } from "./_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="vh-100 dashboard-wrapper DashboardLayout">
    <header className="header-bar">
        <div className="regular-toolbar">
            <div className="header-left">
                <div className="search-filter">
                    <div className="search-field">
                    <input type="text" placeholder="Search here..."/>
                    <i className="search-icon">
                        <Image src={"/assets/images/search.svg"} alt="search" width={12} height={12}/>
                    </i>
                    </div>
                </div>
            </div>
            <div className="header-right">
            <HeaderRight/>
            </div>
        </div>
    </header>

    <div className="dashboard-row gap-29 d-flex justify-content-between">
             <Sidebar/>
                <div className="right-data max-right-width">
                    <div className={`block-right-side`} style={{position:"static"}}
                    >
                        {children}  
                    </div>
                </div>
            </div>
    </div>
  );
}
